### ISSUE TITLE
change job_scheduler_rebuild_all to use state, not settings

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/job_scheduler#4]
I notice that it keeps flipping back and forth from FALSE to TRUE depending on what I've been doing with imports lately. state_set() and state_get() seem more appropriate.

**Comment by bradbulger** [comment]
If this seems like an OK change, I will see if I can do it - haven't attempted the pull request stuff yet.

**Comment by docwilmot** [comment]
Your PR makes sense, I guess; I didnt port this, dont use it and only did some commits because the old maintainer disappeared. So I'm not even going to test it, TBH.

One thing though before I commit it, I think since that was the only variable in the config, best delete the config file, folder, and the `hook_config_info()`.

**Comment by bradbulger** [comment]
I thought so too, but no - the class stores the schedules in the config file, eg "job_scheduler_class_feeds_source_import". So I just clear out the rebuild_all setting.

**Comment by docwilmot** [comment]
Merged.
